// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package macropaygo

import (
	"github.com/web3group/macropay-go-main/internal/config"
	"github.com/web3group/macropay-go-main/internal/hooks"
)

type CustomerPortal struct {
	BenefitGrants   *MacropayBenefitGrants
	Customers       *MacropayCustomers
	CustomerMeters  *MacropayCustomerMeters
	Seats           *Seats
	CustomerSession *CustomerSession
	Downloadables   *Downloadables
	LicenseKeys     *MacropayLicenseKeys
	Members         *MacropayMembers
	Orders          *MacropayOrders
	Organizations   *MacropayOrganizations
	Subscriptions   *MacropaySubscriptions
	Wallets         *Wallets

	rootSDK          *Macropay
	sdkConfiguration config.SDKConfiguration
	hooks            *hooks.Hooks
}

func newCustomerPortal(rootSDK *Macropay, sdkConfig config.SDKConfiguration, hooks *hooks.Hooks) *CustomerPortal {
	return &CustomerPortal{
		rootSDK:          rootSDK,
		sdkConfiguration: sdkConfig,
		hooks:            hooks,
		BenefitGrants:    newMacropayBenefitGrants(rootSDK, sdkConfig, hooks),
		Customers:        newMacropayCustomers(rootSDK, sdkConfig, hooks),
		CustomerMeters:   newMacropayCustomerMeters(rootSDK, sdkConfig, hooks),
		Seats:            newSeats(rootSDK, sdkConfig, hooks),
		CustomerSession:  newCustomerSession(rootSDK, sdkConfig, hooks),
		Downloadables:    newDownloadables(rootSDK, sdkConfig, hooks),
		LicenseKeys:      newMacropayLicenseKeys(rootSDK, sdkConfig, hooks),
		Members:          newMacropayMembers(rootSDK, sdkConfig, hooks),
		Orders:           newMacropayOrders(rootSDK, sdkConfig, hooks),
		Organizations:    newMacropayOrganizations(rootSDK, sdkConfig, hooks),
		Subscriptions:    newMacropaySubscriptions(rootSDK, sdkConfig, hooks),
		Wallets:          newWallets(rootSDK, sdkConfig, hooks),
	}
}
