// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"github.com/web3group/macropay-go-main/models/components"
)

type CustomerPortalLicenseKeysActivateResponse struct {
	HTTPMeta components.HTTPMetadata `json:"-"`
	// Successful Response
	LicenseKeyActivationRead *components.LicenseKeyActivationRead
}

func (c *CustomerPortalLicenseKeysActivateResponse) GetHTTPMeta() components.HTTPMetadata {
	if c == nil {
		return components.HTTPMetadata{}
	}
	return c.HTTPMeta
}

func (c *CustomerPortalLicenseKeysActivateResponse) GetLicenseKeyActivationRead() *components.LicenseKeyActivationRead {
	if c == nil {
		return nil
	}
	return c.LicenseKeyActivationRead
}
