// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"github.com/web3group/macropay-go-main/models/components"
)

type LicenseKeysDeactivateResponse struct {
	HTTPMeta components.HTTPMetadata `json:"-"`
}

func (l *LicenseKeysDeactivateResponse) GetHTTPMeta() components.HTTPMetadata {
	if l == nil {
		return components.HTTPMetadata{}
	}
	return l.HTTPMeta
}
