// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"github.com/web3group/macropay-go-main/models/components"
)

type RefundsCreateResponse struct {
	HTTPMeta components.HTTPMetadata `json:"-"`
	// Refund created.
	Refund *components.Refund
}

func (r *RefundsCreateResponse) GetHTTPMeta() components.HTTPMetadata {
	if r == nil {
		return components.HTTPMetadata{}
	}
	return r.HTTPMeta
}

func (r *RefundsCreateResponse) GetRefund() *components.Refund {
	if r == nil {
		return nil
	}
	return r.Refund
}
