// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"github.com/web3group/macropay-go-main/models/components"
)

type WebhooksDeleteWebhookEndpointRequest struct {
	// The webhook endpoint ID.
	ID string `pathParam:"style=simple,explode=false,name=id"`
}

func (w *WebhooksDeleteWebhookEndpointRequest) GetID() string {
	if w == nil {
		return ""
	}
	return w.ID
}

type WebhooksDeleteWebhookEndpointResponse struct {
	HTTPMeta components.HTTPMetadata `json:"-"`
}

func (w *WebhooksDeleteWebhookEndpointResponse) GetHTTPMeta() components.HTTPMetadata {
	if w == nil {
		return components.HTTPMetadata{}
	}
	return w.HTTPMeta
}
