// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

import (
	"encoding/json"
	"fmt"
)

type CheckoutStatus string

const (
	CheckoutStatusOpen      CheckoutStatus = "open"
	CheckoutStatusExpired   CheckoutStatus = "expired"
	CheckoutStatusConfirmed CheckoutStatus = "confirmed"
	CheckoutStatusSucceeded CheckoutStatus = "succeeded"
	CheckoutStatusFailed    CheckoutStatus = "failed"
)

func (e CheckoutStatus) ToPointer() *CheckoutStatus {
	return &e
}
func (e *CheckoutStatus) UnmarshalJSON(data []byte) error {
	var v string
	if err := json.Unmarshal(data, &v); err != nil {
		return err
	}
	switch v {
	case "open":
		fallthrough
	case "expired":
		fallthrough
	case "confirmed":
		fallthrough
	case "succeeded":
		fallthrough
	case "failed":
		*e = CheckoutStatus(v)
		return nil
	default:
		return fmt.Errorf("invalid value for CheckoutStatus: %v", v)
	}
}
