// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

import (
	"github.com/web3group/macropay-go-main/internal/utils"
	"github.com/web3group/macropay-go-main/types"
)

type CountAggregation struct {
	func_ *string `const:"count" json:"func"`
}

func (c CountAggregation) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(c, "", false)
}

func (c *CountAggregation) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &c, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (c *CountAggregation) GetFunc() *string {
	return types.Pointer("count")
}
