// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

import (
	"encoding/json"
	"fmt"
)

type CustomerSortProperty string

const (
	CustomerSortPropertyCreatedAt      CustomerSortProperty = "created_at"
	CustomerSortPropertyMinusCreatedAt CustomerSortProperty = "-created_at"
	CustomerSortPropertyEmail          CustomerSortProperty = "email"
	CustomerSortPropertyMinusEmail     CustomerSortProperty = "-email"
	CustomerSortPropertyName           CustomerSortProperty = "name"
	CustomerSortPropertyMinusName      CustomerSortProperty = "-name"
)

func (e CustomerSortProperty) ToPointer() *CustomerSortProperty {
	return &e
}
func (e *CustomerSortProperty) UnmarshalJSON(data []byte) error {
	var v string
	if err := json.Unmarshal(data, &v); err != nil {
		return err
	}
	switch v {
	case "created_at":
		fallthrough
	case "-created_at":
		fallthrough
	case "email":
		fallthrough
	case "-email":
		fallthrough
	case "name":
		fallthrough
	case "-name":
		*e = CustomerSortProperty(v)
		return nil
	default:
		return fmt.Errorf("invalid value for CustomerSortProperty: %v", v)
	}
}
