// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

import (
	"encoding/json"
	"fmt"
)

type FileServiceTypes string

const (
	FileServiceTypesDownloadable       FileServiceTypes = "downloadable"
	FileServiceTypesProductMedia       FileServiceTypes = "product_media"
	FileServiceTypesOrganizationAvatar FileServiceTypes = "organization_avatar"
)

func (e FileServiceTypes) ToPointer() *FileServiceTypes {
	return &e
}
func (e *FileServiceTypes) UnmarshalJSON(data []byte) error {
	var v string
	if err := json.Unmarshal(data, &v); err != nil {
		return err
	}
	switch v {
	case "downloadable":
		fallthrough
	case "product_media":
		fallthrough
	case "organization_avatar":
		*e = FileServiceTypes(v)
		return nil
	default:
		return fmt.Errorf("invalid value for FileServiceTypes: %v", v)
	}
}
