// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

import (
	"encoding/json"
	"fmt"
)

type LicenseKeyStatus string

const (
	LicenseKeyStatusGranted  LicenseKeyStatus = "granted"
	LicenseKeyStatusRevoked  LicenseKeyStatus = "revoked"
	LicenseKeyStatusDisabled LicenseKeyStatus = "disabled"
)

func (e LicenseKeyStatus) ToPointer() *LicenseKeyStatus {
	return &e
}
func (e *LicenseKeyStatus) UnmarshalJSON(data []byte) error {
	var v string
	if err := json.Unmarshal(data, &v); err != nil {
		return err
	}
	switch v {
	case "granted":
		fallthrough
	case "revoked":
		fallthrough
	case "disabled":
		*e = LicenseKeyStatus(v)
		return nil
	default:
		return fmt.Errorf("invalid value for LicenseKeyStatus: %v", v)
	}
}
