// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

// OrderInvoice - Order's invoice data.
type OrderInvoice struct {
	// The URL to the invoice.
	URL string `json:"url"`
}

func (o *OrderInvoice) GetURL() string {
	if o == nil {
		return ""
	}
	return o.URL
}
