// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

import (
	"encoding/json"
	"fmt"
)

type OrderBillingReason string

const (
	OrderBillingReasonPurchase           OrderBillingReason = "purchase"
	OrderBillingReasonSubscriptionCreate OrderBillingReason = "subscription_create"
	OrderBillingReasonSubscriptionCycle  OrderBillingReason = "subscription_cycle"
	OrderBillingReasonSubscriptionUpdate OrderBillingReason = "subscription_update"
)

func (e OrderBillingReason) ToPointer() *OrderBillingReason {
	return &e
}
func (e *OrderBillingReason) UnmarshalJSON(data []byte) error {
	var v string
	if err := json.Unmarshal(data, &v); err != nil {
		return err
	}
	switch v {
	case "purchase":
		fallthrough
	case "subscription_create":
		fallthrough
	case "subscription_cycle":
		fallthrough
	case "subscription_update":
		*e = OrderBillingReason(v)
		return nil
	default:
		return fmt.Errorf("invalid value for OrderBillingReason: %v", v)
	}
}
