// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

import (
	"encoding/json"
	"fmt"
)

type SubType string

const (
	SubTypeUser         SubType = "user"
	SubTypeOrganization SubType = "organization"
)

func (e SubType) ToPointer() *SubType {
	return &e
}
func (e *SubType) UnmarshalJSON(data []byte) error {
	var v string
	if err := json.Unmarshal(data, &v); err != nil {
		return err
	}
	switch v {
	case "user":
		fallthrough
	case "organization":
		*e = SubType(v)
		return nil
	default:
		return fmt.Errorf("invalid value for SubType: %v", v)
	}
}
