// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package apierrors

import (
	"encoding/json"
	"github.com/macrodeep/macropay-go/models/components"
)

type HTTPValidationError struct {
	Detail []components.ValidationError `json:"detail,omitempty"`
}

var _ error = &HTTPValidationError{}

func (e *HTTPValidationError) Error() string {
	data, _ := json.Marshal(e)
	return string(data)
}
